### ISSUE TITLE
clrcore: NullReferenceException when using `await Delay(0);` on a background thread

### ISSUE THREAD

**Issue by bladecoding** [citizenfx/fivem#1294]
`ms_delays` in InternalManager is modified on both the main thread and background threads without any locking. This can cause ticks to break with a `SCRIPT ERROR in tick: System.NullReferenceException: Object reference not set to an instance of an object` exception printed every tick and can also lead to a segfault.

This is the code to reproduce the issue

```csharp
    public class ServerMain : BaseScript
    {
        public ServerMain()
        {
            Console.WriteLine("Main: " + Thread.CurrentThread.ManagedThreadId);

            Tick += ServerMain_Tick;

            ThreadPool.SetMinThreads(50, 50);
            ThreadPool.SetMaxThreads(1000, 1000);
        }
        int num;
        private async Task ServerMain_Tick() {
            Console.WriteLine("num " + num);
            for (int i = 0; i < 50; i++) {
                Task.Run(async () => {
                    await Delay(0);
                    num++;
                });
            }
        }
    }
```
![wS0GYIkayD](https://user-images.githubusercontent.com/130197/153730259-a3d0022a-7057-4f28-9d2c-b859495db913.png)

**Comment by Keyinator** [comment]
Have this error on my server. Crashes when you reload or after a longer time of use.

**Comment by blattersturm** [comment]
One thing that confuses me is that there've been multiple cases where this was fixed, or a lack of `lock` statements looked into. Did this regress at some point again?

**Comment by Keyinator** [comment]
> I have been rewriting the whole database to be synchronous since most calls where to that database. Our most used functions where killEvents sent from the client to the server which where handled with a `Task.Run(async() =>{})` (and delays to get player information). Now we do not get any crashes afaict but we have a huge amount of hitch warnings (being 150-200ms). So I don't think this is a viable solution for long term.

Even though now we haven't seen any of those exceptions, we still get those when reloading the script. So it might even reappear spontaniously.

**Comment by bladecoding** [comment]
> One thing that confuses me is that there've been multiple cases where this was fixed, or a lack of `lock` statements looked into. Did this regress at some point again?

I don't think this was ever fixed as the code hasn't changed since the last time it was brought up(April 2020 in discord). At the time I was busy and didn't put together a repo and post it on the forum. Honestly I'm surprised that more people haven't hit this and reported it in 2 years.

**Comment by Keyinator** [comment]
> > One thing that confuses me is that there've been multiple cases where this was fixed, or a lack of `lock` statements looked into. Did this regress at some point again?
> 
> I don't think this was ever fixed as the code hasn't changed since the last time it was brought up(April 2020 in discord). At the time I was busy and didn't put together a repo and post it on the forum. Honestly I'm surprised that more people haven't hit this and reported it in 2 years.

From my experience the error message does not give enough information. For days if not weeks I thought it was me and I even redid a lot of the framework. Maybe the error message should say something to the extend of "A native encountered an error". But this is probably another topic.

**Comment by blattersturm** [comment]
> Maybe the error message should say something to the extend of "A native encountered an error". 

That'd be just as incorrect, since it's not 'a native' encountering an error. In addition to that, this error condition _shouldn't be possible in the first place_, so it's not something that can even be taken into account in advance.

> I don't think this was ever fixed as the code hasn't changed since the last time it was brought up(April 2020 in discord). At the time I was busy and didn't put together a repo and post it on the forum. Honestly I'm surprised that more people haven't hit this and reported it in 2 years.

That's.. weird. I do remember seeing multiple forum posts in the meantime and actually looking into this/adding more lock statements at some point, but maybe that was another collection entirely, or they ended up lost in a local working tree never added to any commit.

**Comment by Keyinator** [comment]
Sorry to bother but has there been any update on this?

When we use await Delay(0) in occasional functions it randomly starts to introduce this error forcing us to restart. https://www.toptal.com/developers/hastebin/redasesoso.sql
Sadly, I can't do a pr since I was unable to get compilation done on my test environment.

One more thing I'd like to note is that it seems appears more fitting to change ms_delays from a List to a ConcurrentBag instead of using locks in the code.
