### ISSUE TITLE
Particles fail to show on Vehicle Mod Bones

### ISSUE THREAD

**Issue by RaidedDesign** [citizenfx/fivem#2003]
Using StartParticleFxLoopedOnEntityBone() fails to show on vehicle bones that have been modified by using SetVehicleMod().

Example: Play the particle on a stock bumper 'bumper_r' using GetEntityBoneIndexByName(ent, 'bumper_r'), and the particle will show as expected.
Swap the rear bumper to a custom bumper, repeat the process and the particles won't show. Note: GetEntityBoneIndexByName() returns the same bone index as the stock bumper.

When checking the indices of exhaust bones ['exhaust', 'exhaust_1'], I noticed that if you swap the exhaust to a custom exhaust with only one exhaust bone, both stock exhaust bones show as valid. I assume SetVehicleMod() is not updating the Entity's bones with the new bones from the Mod piece, hence why the Particle system doesn't show on the new bones.

**Comment by AdrianIsBored** [comment]
I was able to reproduce this, though I'm not sure if this is a bug or not, though it only seems to happen to some vehicles and not to others, for example the: "rapidgt3" and "calico" are affected but "entityxf" isn't (perhaps related to the vehicles and the mod themselves? Is the bone attached to the rear bumper? bumper being replaced? etc...) 

Using [GetWorldPositionOfEntityBone](https://docs.fivem.net/natives/?_0x44A8FCB8ED227738) and drawing a sphere at the returned coordinates doesn't seem to be affected.

https://github.com/citizenfx/fivem/assets/54457761/6c20e581-f741-4712-b45d-ea6b5df5197d
https://github.com/citizenfx/fivem/assets/54457761/0b9386e4-1b33-4b76-bc7f-582f37e3429c

**Comment by RaidedDesign** [comment]
That workaround isn't really useful, as the coords it's outputting is of the old bone and doesn't include any new bones that should be added with the modkit. I believe the issue is when a new modkit is applied that hides / replaces a bone, it doesn't update the entity's bone list.

My actual use-case is displaying particles on exhaust bones. I am aware of SetVehicleNitroEnabled() however this native has a really small render distance, might be due to onesync.

Basically, any new exhaust added to the vehicle could be in the wrong place.
![image](https://github.com/citizenfx/fivem/assets/23512637/13823236-891a-41d0-a4c9-8c5d6e04bdb7)
The output of this exhaust mod.
`
exhausts[
  ("exhaust","exhaust_1","exhaust_2","exhaust_3","exhaust_4","exhaust_5","exhaust_6","exhaust_7")
];
boneIndices[(23, -1, -1, -1, -1, -1, -1, -1)];
boneCoords[
  ([-486.8251647949219, -200.2526092529297, 36.207332611083984],
  [0, 0, 0],
  [0, 0, 0],
  [0, 0, 0],
  [0, 0, 0],
  [0, 0, 0],
  [0, 0, 0],
  [0, 0, 0])
];`

**Comment by gottfriedleibniz** [comment]
Most `ENTITY_BONE` natives aren't really designed for this use-case (dynamic interaction w/ `carcols + turnOffBones`). Note, the following addresses are 1604.

For example, in `Update` the bone's matrix is zeroed (besides its translation) due to `turnOffBones` (`0x140F60664`). Shortly after the ptfx will be disposed of due to the matrix being zeroed (`0x1415EECD5`). Only later do the scene update extensions (or dependency bits) update that matrix to account for the modkit changes. This is besides the few hacks in this path too.

One potential solution here is to provide a native that wraps `0x140F304A0` - it is used elsewhere in game-code (backfire, exhaust, etc) to extract bone-indices (and potentially its transformation matrix). These bones should be usable by `StartParticleFxLoopedOnEntityBone`, etc. Just reference `0x140DC6680` for its use.

**Comment by RaidedDesign** [comment]
> 0x140DC6680

I appreciate the insight, though I've never delved into game code, I wouldn't really know where to start

**Comment by gottfriedleibniz** [comment]
If the rendering distance of the `veh_nitrous` is actually the issue, and custom effects are not desired/required, then that distance check can be stubbed with another variable (`0x140DDFBD8; 1604`). Although, my initial impression was that something more complicated is desired.

**Comment by RaidedDesign** [comment]
Yeah honestly, the only real issue for me is the render distance on SetVehicleNitroEnabled(). Particles can be swapped out somewhat easily with a custom file. Though as I stated, I'm not familiar with core gta and how to access those addresses.

**Comment by gottfriedleibniz** [comment]
3095 included a variety of vehicle related natives (some already implemented by FiveM!) that I think would be valuable to back-port to prior versions. For example, `0x3EE18B00CD86C54F` and `0xE728F090D538CB18` would be quite useful in this case.

**Comment by gottfriedleibniz** [comment]
Should be fixed with 730bb5abb84effab241604e2889b60a556fec728

**Comment by mikigoalie** [comment]
Does not seem to be fixed. Tested on  b10018 the exhaust bone is still not updated

**Comment by lemoncity-rp** [comment]
Not fixed in game build 3095 and b11895. The exhaust bone when changed is not updated and the bone remain the same as the original exhaust, GetEntityBoneIndexByName and GetWorldPositionOfEntityBone return incorrect value.

**Comment by HardstylesDev** [comment]
Can confirm it has not been fixed.

**Comment by mikigoalie** [comment]
Can we reopen this issue? @gottfriedleibniz

**Comment by iWanheda** [comment]
@gottfriedleibniz Hey mate just to bring attention back to this issue, still not fixed.
