### ISSUE TITLE
Facial Animations Sync

### ISSUE THREAD

**Issue by DerekNL** [citizenfx/fivem#2192]
There seems to be an issue with the voice feature in the latest game build (2944), where the mouth movement of other characters does not sync with their speech when you talk. I have tested this on both game build (2802) and game build (2944), and in build 2802, the mouths of other characters move correctly when they speak. However, in build 2944, this issue persists.

**Details - Test #1:**
- Server Artifacts: 6681
- Game Build: 2944 (San Andreas Mercenaries)
- Voice: `pma-voice`
- Speech: The mouth movement does not sync with another player, but your own mouth moves.

**Details - Test #2:**
- Server Artifacts: 6681
- Game Build: 2802 (Los Santos Drug Wars)
- Voice: `pma-voice`
- Speech: The mouth movement moves when you are alone and when other players are talking around you.

**Comment by gottfriedleibniz** [comment]
The [isPlayerTalking](https://github.com/citizenfx/fivem/blob/master/code/components/gta-net-five/src/MumbleVoice.cpp#L716) playerInfo logic should probably be rewritten at this point. 2944 requires another -8, I guess, but `playerInfo` does not actually point to `CPlayerInfo` (nor does it in any recent-ish build).

**Comment by IAmBiti** [comment]
some fix?

**Comment by Arckyzs** [comment]
Any update or alternative to fix this?

**Comment by QBLes** [comment]
This is still a issue im sure its the game build its self, bit of a pain this one..

**Comment by Duderocktv** [comment]
Problem still persists:


    Server Artifacts: 6947
    Game Build: 2944 (San Andreas Mercenaries)
    Voice: pma-voice
    Speech: The mouth movement does not sync with another player, but your own mouth moves.

**Comment by Disquse** [comment]
@Duderocktv Are you on canary?

**Comment by Duderocktv** [comment]
> @Duderocktv Are you on canary?

No sir, I am on Release.
I changed my build to 2802 and my players logged in and the facial animations worked.
Back to 2944 and the issue returns.

Do we need to be on canary?

**Comment by Disquse** [comment]
I believe there wasn't a prod push so far.

**Comment by czatinn** [comment]
Someone fixed that?

**Comment by RogTV** [comment]
Made a fix on my profile

**Comment by Disquse** [comment]
@RogTV There's no need for any script-level fixes, prod push was today and this issue must be fixed now for everyone. If there's still any issues please report it.

**Comment by RogTV** [comment]
@Disquse I posted the fix because I tried again this afternoon and still had the problem. I'll try again tomorrow!

**Comment by Duderocktv** [comment]
Issue still persists for us as well after production push.

    Server Artifacts: 7080
    Game Build: 2944
    Voice: pma-voice
    Speech: The mouth movement moves only for yourself and not for players around you.

**Comment by hjklwasntavailable** [comment]
@Disquse was wrong, there wasn't a production push.

**Comment by RogTV** [comment]
@hjklwasntavailable don't worry my fix is still online

**Comment by Disquse** [comment]
@hjklwasntavailable yeah, you're right.

**Comment by Arckyzs** [comment]
@RogTV, I'm trying to use your fix under PMA-Voice but I'm not sure about the instruction below:
"If You're using pma-voice use this instead of "SaltyChat_TalkStateChanged". You need to add TriggerEvent("rog:userTalking",lastTalkingStatus) in pma-voice/client/init/proximity.lua/129 and it should work "

Updating the mentionned file, not sure how this should be inserted, I did as below but that doesn't fix the sync issue:
`CreateThread(function()
	TriggerEvent('chat:addSuggestion', '/muteply', 'Mutes the player with the specified id', {
		{ name = "player id", help = "the player to toggle mute" },
		{ name = "duration", help = "(opt) the duration the mute in seconds (default: 900)" }
	})
	while true do
		-- wait for mumble to reconnect
		while not MumbleIsConnected() do
			Wait(100)
		end
		-- Leave the check here as we don't want to do any of this logic 
		if GetConvarInt('voice_enableUi', 1) == 1 then
			local curTalkingStatus = MumbleIsPlayerTalking(PlayerId()) == 1
			if lastRadioStatus ~= radioPressed or lastTalkingStatus ~= curTalkingStatus then
				lastRadioStatus = radioPressed
				lastTalkingStatus = curTalkingStatus
				sendUIMessage({
					usingRadio = lastRadioStatus,
					talking = lastTalkingStatus
				})
				TriggerEvent("rog:userTalking",lastTalkingStatus)	
			end
		end

		if voiceState == "proximity" then
			addNearbyPlayers()
			-- What a name, wowza
			local cam = GetConvarInt("voice_disableAutomaticListenerOnCamera", 0) ~= 1 and GetRenderingCam() or -1
			local isSpectating = NetworkIsInSpectatorMode() or cam ~= -1
			if not isListenerEnabled and (isSpectating or listenerOverride) then
				setSpectatorMode(true)
			elseif isListenerEnabled and not isSpectating and not listenerOverride then
				setSpectatorMode(false)
			end
		end

		Wait(GetConvarInt('voice_refreshRate', 200))
	end
end)`

**Comment by Duderocktv** [comment]
Do we know when the next production fix is?
We cannot use 'facial animations' using the temporary fix resource.
Players are curious about a rough eta

**Comment by Disquse** [comment]
I believe this should've been fixed now, prod push was definitely made.

**Comment by Lynxxz** [comment]
What version of server build is this fixed?

**Comment by Disquse** [comment]
It's client fix, not server

**Comment by Lynxxz** [comment]
So its automatically applied to all right?

**Comment by scoobydobedooo** [comment]
2024 and still this issue goes on

**Comment by Gameadictive** [comment]
The issues is still going.

**Comment by alberttheprince** [comment]
> The issues is still going.

It's actually fixed, but I think you really need to scream in your mic for detection. Regularly talking will trigger mouth anims, you really need to scream/talking in a loud voice. Try it out.

**Comment by Gameadictive** [comment]
> > The issues is still going.
> 
> It's actually fixed, but I think you really need to scream in your mic for detection. Regularly talking will trigger mouth anims, you really need to scream/talking in a loud voice. Try it out.

Is fixed NICE!!
