### ISSUE TITLE
Constant Client Crash with Error `beryllium-freddie-eleven`

### ISSUE THREAD

**Issue by kerminal** [citizenfx/fivem#2665]
### What happened?

A player on our server is experiencing consistent client crashes with the error beryllium-freddie-eleven. The crash occurs as soon as they get in the game and the environment loads properly. The crash dumps have been collected and are attached below.

### Expected result

The player should be able to join the game and play without encountering a crash.

### Reproduction steps

1. Player launches the FiveM client on any build (Release, Beta & Unstable)
2. Player connects to our server.
3. The game environment loads.
4. The client crashes with the error `beryllium-freddie-eleven`.

### Importancy

Crash

### Area(s)

FiveM

### Specific version(s)

FiveM 3095

### Additional information

Error in the logs after loading and initializing and even joining mumble is below.

```
[ 81500] [b3095_DumpServ] 34596/ Process crash captured. Crash dialog content: 
[ 81500] [b3095_DumpServ] 34596/ GTA5_b3095.exe!sub_141311F8O (0x1f6f) 
[ 81500] [b3095_DumpServ] 34596/ An error at GTA5_b3095.exe!sub_141311F8O (0x1f6f) caused FiveM to stop working. A crash report is being uploaded to the FiveM developers. 
[ 81516] [b3095_DumpServ] 34596/ Legacy crash hash: beryllium-freddie-eleven 
[ 81516] [b3095_DumpServ] 34596/ Stack trace: 
[ 81516] [b3095_DumpServ] 34596/ GTA5_b3095.exe!sub_1413113D1C (0x10) 
[ 81516] [b3095_DumpServ] 34596/ GTA5_b3095.exe!StartAddress (0xfd) 
[ 81516] [b3095_DumpServ] 34596/ gta-core-five.dll!<lambda>::operator() (0xfa)
```

[CfxCrashDump_2024_07_23_14_34_09.zip](https://github.com/user-attachments/files/16352593/CfxCrashDump_2024_07_23_14_34_09.zip)
[CfxCrashDump_2024_07_23_14_27_43.zip](https://github.com/user-attachments/files/16352594/CfxCrashDump_2024_07_23_14_27_43.zip)
[CfxCrashDump_2024_07_22_21_46_13.zip](https://github.com/user-attachments/files/16352595/CfxCrashDump_2024_07_22_21_46_13.zip)

Crash dumps from the player should be attached.

Player reports other servers do not crash him with this error but every time he joins our server it is the same issue.

Game Build 3095
Servers Artifact is 8823

An old CFX member named `gottfriedleibniz` was interested in if anyone was getting this crash repeatedly as they were "chasing a lead"

![image](https://github.com/user-attachments/assets/c63d0ae2-a73b-4642-92b8-026b0d8de21e)

**Comment by Legacy-TacticalGamingInteractive** [comment]
What client mods are they running.

**Comment by kerminal** [comment]
> What client mods are they running.

None. Fresh GTA 5 install as well as fresh FiveM client install multiple times. Same reuslt.

**Comment by prikolium-cfx** [comment]
> > What client mods are they running.
> 
> None. Fresh GTA 5 install as well as fresh FiveM client install multiple times. Same reuslt.

His game installation and FiveM installation located on different drives, right? And if so can you ask him to move FiveM installation to another drive, because from all the reasons that I can find I can only think that his drive is slowly dying.

**Comment by kerminal** [comment]
> > > What client mods are they running.
> > 
> > 
> > None. Fresh GTA 5 install as well as fresh FiveM client install multiple times. Same reuslt.
> 
> His game installation and FiveM installation located on different drives, right? And if so can you ask him to move FiveM installation to another drive, because from all the reasons that I can find I can only think that his drive is slowly dying.

Player is currently using a singular drive for everything. Other servers work, just not ours with this error.

I've informed the player of your response and said he will try to invest in another drive and try that out.

**Comment by MaitreDam** [comment]
Hello, I have the same problem. Did you know a solution ?

**Comment by prikolium-cfx** [comment]
> Hello, I have the same problem. Did you know a solution ?

Does it happen when you connect to any server, or only one?

**Comment by prikolium-cfx** [comment]
> Hello, I have the same problem. Did you know a solution ?



> > What client mods are they running.
> 
> None. Fresh GTA 5 install as well as fresh FiveM client install multiple times. Same reuslt.

Can you both please try our "Latest" branch of FiveM please?

**Comment by kerminal** [comment]
> > Hello, I have the same problem. Did you know a solution ?
> 
> > > What client mods are they running.
> > 
> > 
> > None. Fresh GTA 5 install as well as fresh FiveM client install multiple times. Same reuslt.
> 
> Can you both please try our "Latest" branch of FiveM please?

@prikolium-cfx Player tried `Latest` branch and got the same crash.

![50b1c26a45f9cb18a7810ef3d44f0b1b-png](https://github.com/user-attachments/assets/27afc0e9-731d-49f7-bf93-661320f396cb)

[CfxCrashDump_2024_07_25_18_36_41.zip](https://github.com/user-attachments/files/16382446/CfxCrashDump_2024_07_25_18_36_41.zip)

**Comment by prikolium-cfx** [comment]
> > > Hello, I have the same problem. Did you know a solution ?
> > 
> > 
> > > > What client mods are they running.
> > > 
> > > 
> > > None. Fresh GTA 5 install as well as fresh FiveM client install multiple times. Same reuslt.
> > 
> > 
> > Can you both please try our "Latest" branch of FiveM please?
> 
> @prikolium-cfx Player tried `Latest` branch and got the same crash.
> 
> ![50b1c26a45f9cb18a7810ef3d44f0b1b-png](https://private-user-images.githubusercontent.com/75539544/352253219-27afc0e9-731d-49f7-bf93-661320f396cb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5OTA3ODYsIm5iZiI6MTcyMTk5MDQ4NiwicGF0aCI6Ii83NTUzOTU0NC8zNTIyNTMyMTktMjdhZmMwZTktNzMxZC00OWY3LWJmOTMtNjYxMzIwZjM5NmNiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDEwNDEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1YWMwMGI5NjBmZWQwOWMxNjc5YzdjYWI4NTFkOTFiYjUyMmY0ZmQxZTcwM2JkZTU5Y2RmYjg5OTBlNmNiZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4kyNy-1c-BIOd8fz6v7UejNJEU2MZCMhhEPKJlv_Wlg)
> 
> [CfxCrashDump_2024_07_25_18_36_41.zip](https://github.com/user-attachments/files/16382446/CfxCrashDump_2024_07_25_18_36_41.zip)

Can you please give it a try using UpdateChannel `specific/feature/update-ros-dll`. Player should change UpdateChannel in CitizenFX.ini to `specific/feature/update-ros-dll` and try to connect to your server.

**Comment by kerminal** [comment]
> > > > Hello, I have the same problem. Did you know a solution ?
> > > 
> > > 
> > > > > What client mods are they running.
> > > > 
> > > > 
> > > > None. Fresh GTA 5 install as well as fresh FiveM client install multiple times. Same reuslt.
> > > 
> > > 
> > > Can you both please try our "Latest" branch of FiveM please?
> > 
> > 
> > @prikolium-cfx Player tried `Latest` branch and got the same crash.
> > ![50b1c26a45f9cb18a7810ef3d44f0b1b-png](https://private-user-images.githubusercontent.com/75539544/352253219-27afc0e9-731d-49f7-bf93-661320f396cb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5OTA3ODYsIm5iZiI6MTcyMTk5MDQ4NiwicGF0aCI6Ii83NTUzOTU0NC8zNTIyNTMyMTktMjdhZmMwZTktNzMxZC00OWY3LWJmOTMtNjYxMzIwZjM5NmNiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDEwNDEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1YWMwMGI5NjBmZWQwOWMxNjc5YzdjYWI4NTFkOTFiYjUyMmY0ZmQxZTcwM2JkZTU5Y2RmYjg5OTBlNmNiZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4kyNy-1c-BIOd8fz6v7UejNJEU2MZCMhhEPKJlv_Wlg)
> > [CfxCrashDump_2024_07_25_18_36_41.zip](https://github.com/user-attachments/files/16382446/CfxCrashDump_2024_07_25_18_36_41.zip)
> 
> Can you please give it a try using UpdateChannel `specific/feature/update-ros-dll`. Player should change UpdateChannel in CitizenFX.ini to `specific/feature/update-ros-dll` and try to connect to your server.

Update for @prikolium-cfx - Still crashes. Ensured the test was used - on client no build is highlighted while loaded into the updatechannel `specific/feature/update-ros-dll`.

![image](https://github.com/user-attachments/assets/6dd8b68b-6e9f-4342-88b3-0a1241f70296)


[CfxCrashDump_2024_07_27_23_55_16.zip](https://github.com/user-attachments/files/16401746/CfxCrashDump_2024_07_27_23_55_16.zip)

**Comment by kerminal** [comment]
My player has reported things are fixed after another reinstall of FiveM and GTA 5.

**Comment by Legacy-TacticalGamingInteractive** [comment]
You closed this but its not really fixed.

I am now getting this on a test server when I go to view certain custom map additions based on North Yankton. Soon as I get near them. Not sure why thats happening. Did you recently install some custom mods on your server.

Reinstalling GTAV/FiveM is a bit drastic. For me, these crashes are new. Running latest canary client build.

**Comment by kerminal** [comment]
> You closed this but its not really fixed.
> 
> I am now getting this on a test server when I go to view certain custom map additions based on North Yankton. Soon as I get near them. Not sure why thats happening. Did you recently install some custom map mods on your server.
> 
> Reinstalling GTAV/FiveM is a bit drastic. For me, these crashes are new. Running latest canary client build.
> 
> ```
> [    441609] [b3095_GTAProce] ResourcePlacementThr/ Physics validation failed for asset ap1_03_td_cpark.ydr.
> [    441609] [b3095_GTAProce] ResourcePlacementThr/ This asset is **INVALID**, but we've fixed it for this load. Please fix the exporter used to export it.
> [    441609] [b3095_GTAProce] ResourcePlacementThr/ Details: Poly 0 edge reference is invalid. It leads to vertex 63539, when there are only 1300 vertices.
> [    442015] [b3095_GTAProce] ResourcePlacementThr/ Physics validation failed for asset cs1_05_clinic_grnd2_ny.ydr.
> [    442015] [b3095_GTAProce] ResourcePlacementThr/ This asset is **INVALID**, but we've fixed it for this load. Please fix the exporter used to export it.
> [    442015] [b3095_GTAProce] ResourcePlacementThr/ Details: Poly 0 edge reference is invalid. It leads to vertex 751, when there are only 434 vertices.
> [    475609] [b3095_GTAProce] ResourcePlacementThr/ Physics validation failed for asset uniqx_burgershot_build01.ydr.
> [    475609] [b3095_GTAProce] ResourcePlacementThr/ This asset is **INVALID**, but we've fixed it for this load. Please fix the exporter used to export it.
> [    475609] [b3095_GTAProce] ResourcePlacementThr/ Details: Poly 38 edge reference is invalid. It leads to vertex 64968, when there are only 669 vertices.
> [    475703] [b3095_GTAProce] ResourcePlacementThr/ Physics validation failed for asset uniqx_burgershot_bigsign.ydr.
> [    475703] [b3095_GTAProce] ResourcePlacementThr/ This asset is **INVALID**, but we've fixed it for this load. Please fix the exporter used to export it.
> [    475703] [b3095_GTAProce] ResourcePlacementThr/ Details: Poly 24 edge reference is invalid. It leads to vertex 1024, when there are only 1002 vertices.
> [    557562] [b3095_GTAProce] ResourcePlacementThr/ Physics validation failed for asset firedept_26_kitchen.ydr.
> [    557562] [b3095_GTAProce] ResourcePlacementThr/ This asset is **INVALID**, but we've fixed it for this load. Please fix the exporter used to export it.
> [    557562] [b3095_GTAProce] ResourcePlacementThr/ Details: Poly 1 edge reference is invalid. It leads to vertex 23409, when there are only 9895 vertices.
> [    558093] [b3095_GTAProce] ResourcePlacementThr/ Physics validation failed for asset uniqx_burgershot_build02.ydr.
> [    558093] [b3095_GTAProce] ResourcePlacementThr/ This asset is **INVALID**, but we've fixed it for this load. Please fix the exporter used to export it.
> [    558093] [b3095_GTAProce] ResourcePlacementThr/ Details: Poly 15 edge reference is invalid. It leads to vertex 65183, when there are only 1364 vertices.
> [    558390] [b3095_GTAProce]                22272/ ResourceCache::AddEntry: Saved cache:v1:bd84cb5d40de696b577e245e58ebfa0a756053fc to the index cache.
> [    558953] [b3095_GTAProce]                 3156/ ResourceCache::AddEntry: Saved cache:v1:9363c355d247612dbfcbaef87227de51663d00ba to the index cache.
> [    559062] [b3095_GTAProce]                20828/ ResourceCache::AddEntry: Saved cache:v1:b9a56fe2b099e202230277e1a591ed565afc837b to the index cache.
> [    559093] [b3095_GTAProce]                22276/ ResourceCache::AddEntry: Saved cache:v1:0f5ff8bfb80f0c4ca1a20e21b95eafec5f33455b to the index cache.
> [    559125] [b3095_GTAProce]                22276/ ResourceCache::AddEntry: Saved cache:v1:834e7a01b51320472d48c8124d1908f2afa20494 to the index cache.
> [    559156] [b3095_GTAProce]                22276/ ResourceCache::AddEntry: Saved cache:v1:abbee4941fd4794b55d4ec4e074cb276f4c06dcb to the index cache.
> [    559250] [b3095_GTAProce]                22276/ ResourceCache::AddEntry: Saved cache:v1:3f2e5e3ecdaf0b73c422189325490a8700cb2d3d to the index cache.
> [    559281] [b3095_GTAProce]                22276/ ResourceCache::AddEntry: Saved cache:v1:4941fad4fa6d8b44671d0e5c935c06cb1b3f3df0 to the index cache.
> [    559297] [b3095_GTAProce]                22276/ ResourceCache::AddEntry: Saved cache:v1:ea6ac62d7952aaed6a32e274bfd21572faa878e8 to the index cache.
> [    559297] [b3095_GTAProce]                22276/ ResourceCache::AddEntry: Saved cache:v1:4d2e085d434ee3dff9c5786207dd4bcc0137e8bf to the index cache.
> [    560547] [b3095_DumpServ]                20960/ Process crash captured. Crash dialog content:
> [    560547] [b3095_DumpServ]                20960/ GTA5_b3095.exe!sub_141311FB0 (0x16f)
> [    560547] [b3095_DumpServ]                20960/ An error at GTA5_b3095.exe!sub_141311FB0 (0x16f) caused FiveM to stop working. A crash report is being uploaded to the FiveM developers.
> [    560547] [b3095_DumpServ]                20960/ 
> [    560547] [b3095_DumpServ]                20960/ Legacy crash hash: beryllium-freddie-eleven
> [    560547] [b3095_DumpServ]                20960/ Stack trace:
> [    560547] [b3095_DumpServ]                20960/   GTA5_b3095.exe!sub_141311FB0 (0x16f)
> [    560547] [b3095_DumpServ]                20960/   GTA5_b3095.exe!sub_141313D1C (0x10)
> [    560547] [b3095_DumpServ]                20960/   GTA5_b3095.exe!StartAddress (0xfd)
> [    560547] [b3095_DumpServ]                20960/   gta-core-five.dll!<lambda>::operator() (0xf4) (<A HREF="https://sourcegraph.com/github.com/citizenfx/fivem/-/blob/master/fivem/code/components/gta-core-five/src/ThreadNames.cpp?L57">ThreadNames.cpp:57</A>)
> [    560547] [b3095_DumpServ]                20960/   KERNEL32.DLL!BaseThreadInitThunk (0x13)
> [    560547] [b3095_DumpServ]                20960/   ntdll.dll!RtlUserThreadStart (0x20)
> [    560547] [b3095_DumpServ]                20960/ 
> [    562578] [b3095_DumpServ]                20960/ Crash report service returned si-35ae25cfcd484c3cba1683ed8fb65a37
> ```

Things change all the time but in the area the player was crashing in (the beach on the west side is where my players first load in) no we don't have anything super special or new over there as of recently. The player found that he was crashing at that same area on other servers and GTA Online, it was just more noticeable on our server because our character select is AT the pier. 

Once the player reinstalled GTA and FiveM they were fixed, no more error and can play just fine. If you still have the issue I suggest opening a new issue and fill everything out properly if you can replicate the error. @Legacy-TacticalGamingInteractive

**Comment by Legacy-TacticalGamingInteractive** [comment]
This was just SPAMMING my client console right before I crashed out
![image](https://github.com/user-attachments/assets/2d2df32c-7fe0-4c5c-8d1a-7b81640e76d9)

some runaway loop?
