### ISSUE TITLE
carolina-december-eight crash

### ISSUE THREAD

**Issue by LegendaryMods** [citizenfx/fivem#3107]
### What happened?

If an NPC shoots another NPC the game will crash. This causes other players in the area to crash, if they're nearby.
I've tested this on multiple game builds (b3095, b3258, b3323 & b3407,) and multiple artifacts, and it seems to only happen on b3407.
I've also tested this across multiple servers, including one with a a fresh install of the Default CFX recipe provided by txAdmin.
This happens on both Linux, and Windows servers. [CfxCrashDump_2025_01_28_18_16_38.zip](https://github.com/user-attachments/files/18577689/CfxCrashDump_2025_01_28_18_16_38.zip)

Edit: Shooting armed NPCs will also cause a crash to happen.
Crash dump from the video below: [CfxCrashDump_2025_01_28_21_09_58.zip](https://github.com/user-attachments/files/18579382/CfxCrashDump_2025_01_28_21_09_58.zip)
https://github.com/user-attachments/assets/b3e5d699-ca40-43ea-af3e-ecefbfd160a8

### Expected result

no crashes

### Reproduction steps

1a. NPC shoots/kills another NPC
1b. Shoot an armed NPC
2. Crash

### Importancy

Crash

### Area(s)

FiveM

### Specific version(s)

FiveM 3407, Server 12508 Linux, Server 12629 Windows

### Additional information

Edit 1: Removed incorrect information & reproduction steps, added more context, and clearer reproduction steps

**Comment by DaniGP17** [comment]
I've tried on b3407 being killed +14 times in the same spot with the same NPCs but I can't reproduce the issue. Am I doing something wrong?

**Comment by CrazedslawDev** [comment]
Ive been consistently getting this issue whenever trying to shoot armed NPCs (specifically altruist cultists or armed bank truck guards as part of a script)

**Comment by DaniGP17** [comment]
I've been investigating for a while but I still haven't found a solution, in case anyone finds this useful:
```
Location: 48 8B 81 ? ? ? ? 4C 8B 90 ? ? ? ? 49 8B 82
Function Name: CPedIntelligence::IsThreatenedBy
Instruction Crash: mov     rax, [rcx+358h]
Reason: rcx = 0000000000000, rcx means self of CPedIntelligence
Called from:
	CPedIntelligence::IsPedThreatening:
		Location: 48 ? ? ? ? 57 48 ? ? ? 41 ? ? 45 ? ? 41 ? ? 48 ? ? c6
		Instruction: call    CPedIntelligence__IsThreatenedBy
		Reason: self is invalid
		Called from:
			CTaskSmartFlee::ShouldConsiderPedThreatening:
				Location: 48 89 5C 24 ? 57 48 83 EC ? 48 8B F9 48 8B 89 ? ? ? ? 48 8B DA E8 ? ? ? ? 84 C0 75 ? 32 C0
				Instruction: call    CPedIntelligence__IsPedThreatening
				Reason: Yet I didn't find the exact cause but I only think about the first argument of ShouldConsiderPedThreatening that is a invalid CPed* or that CPed is a valid pointer but miss the m_pPedIntelligence
```
Maybe my research is wrong but I hope it can help.

**Comment by topordenis** [comment]
> IsThreatenedBy

please avoid copying function names from leak

**Comment by xDoctor0** [comment]
Same thing happend to me when NPC's shot me

**Comment by dewrongta** [comment]
Any solution?

**Comment by jonkthx** [comment]
Exact same error here. Gamebuild 3407 and artifact version 13068

**Comment by randomuser2748** [comment]
Same error, happens anytime me or anyone else shoots an armed NPC, regardless of what or how many resources are loaded. Is there a timeline for when this will be fixed?

**Comment by epyidev** [comment]
Same error, i am just forced to not use the latest build for the moment

**Comment by devmailar** [comment]
Same error, everytime I fight with armed NPC, I crash on the latest build

**Comment by TheGoatRico** [comment]
Downgrading to Build: 3095 & Artifact: 13068 stopped the issue for me.

**Comment by Kayseh** [comment]
still having this issue on the latest build

**Comment by INFIERNOXIII** [comment]
same issue here artifact b13227 & gamebuild 3407
no issue using 3258

[CfxCrashDump_2025_03_17_02_42_59.zip](https://github.com/user-attachments/files/19277788/CfxCrashDump_2025_03_17_02_42_59.zip)

**Comment by hmilan8** [comment]
same issue.

**Comment by iridium-cfx** [comment]
This was fixed in a71a8e822087f2c85bf38d50199848e3f484322b

**Comment by gtarps** [comment]
Hi @iridium-cfx - this is still an issue with artifact version 13890 for Linux. Players crash when aiming at weapon at an armed ped.

**Log Snippet:**

`[    176125] [b3407_DumpServ]                16928/ Process crash captured. Crash dialog content:
[    176125] [b3407_DumpServ]                16928/ GTA5_b3407.exe!sub_140721238 (0x2f)
[    176125] [b3407_DumpServ]                16928/ An error at GTA5_b3407.exe!sub_140721238 (0x2f) caused FiveM to stop working. A crash report is being uploaded to the FiveM developers.
[    176125] [b3407_DumpServ]                16928/ 
[    176125] [b3407_DumpServ]                16928/ Legacy crash hash: carolina-december-eight
[    176125] [b3407_DumpServ]                16928/ Stack trace:
[    176125] [b3407_DumpServ]                16928/   GTA5_b3407.exe!sub_140721238 (0x2f)
[    176125] [b3407_DumpServ]                16928/   GTA5_b3407.exe!sub_14071FAF8 (0x1f)
[    176125] [b3407_DumpServ]                16928/   GTA5_b3407.exe!sub_140C3C2A4 (0x1b)
[    176125] [b3407_DumpServ]                16928/   0x3f00a8353f576613
[    176125] [b3407_DumpServ]                16928/   0x4201ce303e4b70d3
[    176125] [b3407_DumpServ]                16928/   0xc3ca1d3444836662
[    176125] [b3407_DumpServ]                16928/   0x3f9a13364285a67b
[    176125] [b3407_DumpServ]                16928/ 
[    181078] [b3407_DumpServ]                16928/ Crash report service returned si-0c4b20c5f26a49029bd4458bca3a7c23`

**Environment Details:**
Node: v16.9.1
OS: Linux 5.15.0-133-generic
Username: okular
CPU Model: AMD EPYC Processor
CPU Stats: 4c/8t - NaN GHz
CPU Usage: 5%
Memory: 8% (2.43/30.60)

**Comment by DaniGP17** [comment]
> Hi @iridium-cfx - this is still an issue with artifact version 13890 for Linux. Players crash when aiming a weapon at an armed ped.

Are you in latest(canary)?

**Comment by gtarps** [comment]
> > Hi [@iridium-cfx](https://github.com/iridium-cfx) - this is still an issue with artifact version 13890 for Linux. Players crash when aiming a weapon at an armed ped.
> 
> Are you in latest(canary)?

My update channel is set to beta.

**Comment by DaniGP17** [comment]
> My update channel is set to beta.

Try using latest because I'm not sure if that fix is already in beta.

**Comment by Valdarix** [comment]
This issue still exists on windows artifact 14033 with game version set to 3407.

**Comment by DaniGP17** [comment]
> This issue still exists on windows artifact 14033 with game version set to 3407.

Are you using latest?

**Comment by Valdarix** [comment]
> > This issue still exists on windows artifact 14033 with game version set to 3407.
> 
> Are you in latest(canary)?

yes

**Comment by iridium-cfx** [comment]
> > > This issue still exists on windows artifact 14033 with game version set to 3407.
> > 
> > 
> > Are you in latest(canary)?
> 
> yes

If you are still crashing, I am fairly sure it isn't from this issue. Even on prod branch it hasn't been seen for 3 days now.

**Comment by TheOnlyNecro** [comment]
Im still crashing on 3407
